name: Run test suite

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  doit:
    name: Test suite
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Build
        run: nix develop --command just build

      - name: Run tests
        run: nix develop --command just test

      - name: Run examples
        run: nix develop --command just examples

      - name: Run macros tests
        run: nix develop --command just test-macros

      - name: Run doc tests
        run: nix develop --command just test-doc
